#!/usr/bin/env bash
#Query domain and its subdomains
print_info() {
	local sub_dom
	local dom

	sub_dom=$2
	dom=$1
	
	local my_str
	local record
	local ip

	my_str=$(dig "$sub_dom.$dom" | grep -A1 'ANSWER SECTION:' | tail -1)
	record=$(echo "$my_str" | cut -f 4)
	ip=$(echo "$my_str" | cut -f 5)	
	echo "$sub_dom $record $ip" |awk '{ print "This subdomain " $1 " is a " $2 " record and points to " $3 }'


}

if [ -n "$1" ]; then
    if [ -n "$2" ]; then
        print_info "$1" "$2"
    else
        print_info "$1" "www"
	print_info "$1" "lb-01"
	print_info "$1" "web-01"
	print_info "$1" "web-02"
    fi
fi
