#!/usr/bin/env bash
#Query domain and its subdomains
print_info() {
	local sub_dom
	local dom

	sub_dom=$2
	dom=$1
	
	local my_str
	
	my_str=$(dig "$sub_dom.$dom" | grep -A1 'ANSWER SECTION:' | tail -1)
	echo "$my_str" |awk -v subd="$sub_dom" '{ print "The subdomain " subd " is a " $4 " record and points to " $5 }'


}

if [ -n "$1" ]; then
    if [ -n "$2" ]; then
        print_info "$1" "$2"
    else
        print_info "$1" "www"
	print_info "$1" "lb-01"
	print_info "$1" "web-01"
	print_info "$1" "web-02"
    fi
fi
