#!/usr/bin/env bash
#This script installs nginx on a server and configures it
#to return a "Hello World!" page
sudo apt update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
