#!/usr/bin/env bash
#Configure nginx to serve the file
echo "server {
   listen 80;
   listen [::]:80;
   root /var/www/html;
   index ret_file.html;
   
   location / {
   add_header X-Served-By $(hostname);
   }

   location / {
     return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
  }
   error_page 404 /custom_404.html;
   location = /custom_404.html {
    root /var/www/html;
    internal;
  }
}" > /etc/nginx/sites-available/default
