#!/usr/bin/env bash
#5-4_bad_luck: Loops from 1 to 10
#and prints "bad luck" for the 4th iteration
#"good luck" for the 8th loop iteration
#and best school for other iterations
i=1
while [ $i -ne 11 ]
do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$((i + 1))
done
