#!/usr/bin/env bash
#6-superstitious: displays numbers 1 through 20
#and displays 4 then "bad luck from China" in the
#4th loop
#displays 9 then "bad luck from Japan" in the 9th
#loop
#and displays 17 then "bad luck from Italy in the 
#17th loop
i=1
while [ $i -ne 21 ]
do
	echo "$i"
	case "$i" in
		"4") echo "bad luck from China"
		;;

		"9") echo "bad luck from Japan"
		;;

		"17") echo "bad luck from Italy"
		;;
	esac
	i=$((i + 1))
done
