#!/usr/bin/env bash
#7-clock: prints the time for 12
#hours and 59 minutes
i=0
while [ $i -ne 13 ] 
do
	echo "Hour: $i"
	j=1
	while [ $j -ne 60 ]
	do
		echo "$j"
		j=$((j + 1))
	done
	i=$((i + 1))
done
	
