#!/usr/bin/env bash
#0-change_your_home_IP: configures an ubuntu server.
cp /etc/hosts ~/hosts.new
sudo sed -i '' 's/localhost/127.0.0.2/g' ~/hosts.new
sudo sed -i '' 's/facebook.com/8.8.8.8/g' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
